# Generated by Django 6.0.6 on 2026-06-16 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paciente', models.IntegerField(unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('imc', models.FloatField()),
                ('presion_sistolica', models.IntegerField()),
                ('presion_diastolica', models.IntegerField()),
                ('frecuencia_cardiaca', models.IntegerField()),
                ('glucosa', models.FloatField()),
                ('colesterol', models.FloatField()),
                ('saturacion_oxigeno', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('antecedentes_familiares', models.BooleanField(default=False)),
                ('fumador', models.BooleanField(default=False)),
                ('consumo_alcohol', models.BooleanField(default=False)),
                ('actividad_fisica', models.CharField(choices=[('sedentario', 'Sedentario'), ('leve', 'Leve'), ('moderado', 'Moderado'), ('intenso', 'Intenso')], default='sedentario', max_length=20)),
                ('diagnostico_preliminar', models.CharField(max_length=200)),
                ('riesgo_enfermedad', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], default='bajo', max_length=10)),
                ('fecha_consulta', models.DateField()),
                ('es_critico', models.BooleanField(default=False)),
                ('clasificacion_imc', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_consulta'],
            },
        ),
        migrations.CreateModel(
            name='ETLLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('iniciado', 'Iniciado'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('error', 'Error')], default='iniciado', max_length=15)),
                ('registros_extraidos', models.IntegerField(default=0)),
                ('registros_transformados', models.IntegerField(default=0)),
                ('registros_cargados', models.IntegerField(default=0)),
                ('registros_duplicados', models.IntegerField(default=0)),
                ('registros_invalidos', models.IntegerField(default=0)),
                ('tiempo_ejecucion', models.FloatField(blank=True, null=True)),
                ('archivo_fuente', models.CharField(blank=True, max_length=255)),
                ('log_detalle', models.TextField(blank=True)),
                ('error_mensaje', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
