# Generated by Django 6.0.6 on 2026-06-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLMetrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modelo', models.CharField(max_length=50)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('confusion_matrix', models.JSONField()),
                ('clases', models.JSONField()),
                ('fecha_entrenamiento', models.DateTimeField(auto_now=True)),
            ],
            options={
                'get_latest_by': 'fecha_entrenamiento',
            },
        ),
    ]
