BEGIN;
--
-- Create model User
--
CREATE TABLE "authentication_user" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL, "role" varchar(20) NOT NULL, "created_at" timestamp with time zone NOT NULL);
CREATE TABLE "authentication_user_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "authentication_user_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "permission_id" integer NOT NULL);
CREATE INDEX "authentication_user_username_a09a089e_like" ON "authentication_user" ("username" varchar_pattern_ops);
ALTER TABLE "authentication_user_groups" ADD CONSTRAINT "authentication_user_groups_user_id_group_id_8af031ac_uniq" UNIQUE ("user_id", "group_id");
ALTER TABLE "authentication_user_groups" ADD CONSTRAINT "authentication_user__user_id_30868577_fk_authentic" FOREIGN KEY ("user_id") REFERENCES "authentication_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "authentication_user_groups" ADD CONSTRAINT "authentication_user_groups_group_id_6b5c44b7_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "authentication_user_groups_user_id_30868577" ON "authentication_user_groups" ("user_id");
CREATE INDEX "authentication_user_groups_group_id_6b5c44b7" ON "authentication_user_groups" ("group_id");
ALTER TABLE "authentication_user_user_permissions" ADD CONSTRAINT "authentication_user_user_user_id_permission_id_ec51b09f_uniq" UNIQUE ("user_id", "permission_id");
ALTER TABLE "authentication_user_user_permissions" ADD CONSTRAINT "authentication_user__user_id_736ebf7e_fk_authentic" FOREIGN KEY ("user_id") REFERENCES "authentication_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "authentication_user_user_permissions" ADD CONSTRAINT "authentication_user__permission_id_ea6be19a_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "authentication_user_user_permissions_user_id_736ebf7e" ON "authentication_user_user_permissions" ("user_id");
CREATE INDEX "authentication_user_user_permissions_permission_id_ea6be19a" ON "authentication_user_user_permissions" ("permission_id");
COMMIT;
