BEGIN;
--
-- Create model Paciente
--
CREATE TABLE "etl_paciente" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "id_paciente" integer NOT NULL UNIQUE, "nombres" varchar(100) NOT NULL, "apellidos" varchar(100) NOT NULL, "edad" integer NOT NULL, "sexo" varchar(1) NOT NULL, "peso" double precision NOT NULL, "altura" double precision NOT NULL, "imc" double precision NOT NULL, "presion_sistolica" integer NOT NULL, "presion_diastolica" integer NOT NULL, "frecuencia_cardiaca" integer NOT NULL, "glucosa" double precision NOT NULL, "colesterol" double precision NOT NULL, "saturacion_oxigeno" double precision NOT NULL, "temperatura" double precision NOT NULL, "antecedentes_familiares" boolean NOT NULL, "fumador" boolean NOT NULL, "consumo_alcohol" boolean NOT NULL, "actividad_fisica" varchar(20) NOT NULL, "diagnostico_preliminar" varchar(200) NOT NULL, "riesgo_enfermedad" varchar(10) NOT NULL, "fecha_consulta" date NOT NULL, "es_critico" boolean NOT NULL, "clasificacion_imc" varchar(30) NOT NULL, "created_at" timestamp with time zone NOT NULL);
--
-- Create model ETLLog
--
CREATE TABLE "etl_etllog" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "fecha_inicio" timestamp with time zone NOT NULL, "fecha_fin" timestamp with time zone NULL, "estado" varchar(15) NOT NULL, "registros_extraidos" integer NOT NULL, "registros_transformados" integer NOT NULL, "registros_cargados" integer NOT NULL, "registros_duplicados" integer NOT NULL, "registros_invalidos" integer NOT NULL, "tiempo_ejecucion" double precision NULL, "archivo_fuente" varchar(255) NOT NULL, "log_detalle" text NOT NULL, "error_mensaje" text NOT NULL, "usuario_id" bigint NULL);
ALTER TABLE "etl_etllog" ADD CONSTRAINT "etl_etllog_usuario_id_0912ca71_fk_authentication_user_id" FOREIGN KEY ("usuario_id") REFERENCES "authentication_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "etl_etllog_usuario_id_0912ca71" ON "etl_etllog" ("usuario_id");
COMMIT;
